//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Edit_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Edit_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\leoju\AppData\Local\Temp\BC3C12366352E815CEEEFEF9F43E82C1C0F3\3\Bump\Bump.EStore.MVC\Views\Categories\Edit.cshtml"
  
    ViewBag.Title = "Edit";


#line default
#line hidden

#line 2 "C:\Users\leoju\AppData\Local\Temp\BC3C12366352E815CEEEFEF9F43E82C1C0F3\3\Bump\Bump.EStore.MVC\Views\Categories\Edit.cshtml"
  
    var options = ViewBag.FirstCategoryName;
    var options2 = ViewBag.SecondCategoryName;
    var options3 = ViewBag.ThirdCategoryName;
    var jsOptions = Newtonsoft.Json.JsonConvert.SerializeObject(options);
    var jsOptions2 = Newtonsoft.Json.JsonConvert.SerializeObject(options2);
    var jsOptions3 = Newtonsoft.Json.JsonConvert.SerializeObject(options3);


#line default
#line hidden

#line 3 "C:\Users\leoju\AppData\Local\Temp\BC3C12366352E815CEEEFEF9F43E82C1C0F3\3\Bump\Bump.EStore.MVC\Views\Categories\Edit.cshtml"
using (Html.BeginForm("Edit", "Categories", FormMethod.Post))
{
    

#line default
#line hidden

#line 4 "C:\Users\leoju\AppData\Local\Temp\BC3C12366352E815CEEEFEF9F43E82C1C0F3\3\Bump\Bump.EStore.MVC\Views\Categories\Edit.cshtml"
                                                                             
    

#line default
#line hidden

#line 5 "C:\Users\leoju\AppData\Local\Temp\BC3C12366352E815CEEEFEF9F43E82C1C0F3\3\Bump\Bump.EStore.MVC\Views\Categories\Edit.cshtml"
          
}

#line default
#line hidden
DefineSection("Scripts", () => {


#line 6 "C:\Users\leoju\AppData\Local\Temp\BC3C12366352E815CEEEFEF9F43E82C1C0F3\3\Bump\Bump.EStore.MVC\Views\Categories\Edit.cshtml"
                 __o = Html.Raw(jsOptions);


#line default
#line hidden

#line 7 "C:\Users\leoju\AppData\Local\Temp\BC3C12366352E815CEEEFEF9F43E82C1C0F3\3\Bump\Bump.EStore.MVC\Views\Categories\Edit.cshtml"
                  __o = Html.Raw(jsOptions2);


#line default
#line hidden

#line 8 "C:\Users\leoju\AppData\Local\Temp\BC3C12366352E815CEEEFEF9F43E82C1C0F3\3\Bump\Bump.EStore.MVC\Views\Categories\Edit.cshtml"
                  __o = Html.Raw(jsOptions3);


#line default
#line hidden
});

}
}
}
